import { Noto_Sans_KR } from 'next/font/google';
import "./globals.css";
import Link from "next/link";
import AirplainStateBox from "@/components/AirplainStateBox";

const notoSansKr = Noto_Sans_KR({
  subsets: ['latin'],
  variable: '--NotoSans'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${notoSansKr.className} antialiased relative`}
      >
        <nav className="fixed flex items-center px-4 py-2 w-full justify-between bg-white z-10 border-b-1">
          <h1 className="font-black">24-2 DB 텀프로젝트 기내식서비스</h1>
          <Link 
            className="bg-gray-100 px-4 py-2 font-black"
            href={'/'}
          >
            메인페이지로 돌아가기
          </Link>
        </nav>
        <div className="px-12 py-16">
          {children}
        </div>
        <AirplainStateBox />
      </body>
    </html>
  );
}
